=== Chicotjr5/ASIR-CETI/ASIR/1º AÑO/Lenguaje de Marcas/UT-6/Schema/Ejercicio_8/Ejercicio8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="resultado" type="tiporesultado"/>

<xs:complexType name="tiporesultado">
	<xs:sequence>
		<xs:element name="libreria" type="tipolibreria" maxOccurs="unbounded"/>
	</xs:sequence>	
	<xs:attribute name="tema" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="tipolibreria">
	<xs:sequence>
		<xs:element name="libro" type="tipolibro" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="nombre" type="xs:string" use="required"/>
	<xs:attribute name="web" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="tipolibro">
	<xs:sequence>
		<xs:element name="titulo" type="xs:string"/>
		<xs:element name="autores" type="tipoautores"/>
		<xs:element name="editorial" type="xs:string"/>
		<xs:element name="anyo" type="xs:int"/>
		<xs:element name="web" type="xs:string"/>
		<xs:element name="precio" type="tipoprecio"/>
	</xs:sequence>
	<xs:attribute name="isbn" type="xs:string"/>
	<xs:attribute name="nivel" type="xs:string"/>
</xs:complexType>

<xs:complexType name="tipoautores">
	<xs:sequence>
		<xs:element name="autor" type="xs:string" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="tipoprecio">
	<xs:simpleContent>
		<xs:extension base="xs:float">
			<xs:attribute name="moneda" type="tipomoneda" use="optional"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<xs:simpleType name="tipomoneda">
	<xs:restriction base="xs:string">
		<xs:enumeration value="Dolar"/>
		<xs:enumeration value="Euro"/>
		<xs:enumeration value="Yen"/>
	</xs:restriction>
</xs:simpleType>
</xs:schema>

=== Chicotjr5/ASIR-CETI/ASIR/1º AÑO/Lenguaje de Marcas/UT-6/Schema/Ejercicio_8/libros_xml.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<resultado tema="XML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Juan%20de%20colonia/1%20A%C3%91O/LM/T6/Ejercicios/SCHEMA/Ejercicio8/Ejercicio8.xsd">
	<libreria nombre="casa del libro" web="www.casadellibro.com">
		<libro isbn="ISBN9788493272074" nivel="avanzado">
			<titulo>SERIE DESARROLLADORES: APLICACIONES XML CON XML SUITE</titulo>
			<autores>
				<autor>varios autores</autor>
			</autores>
			<editorial>DANYSOFT 2016</editorial>
			<anyo>2018</anyo>
			<web>   http://www.casadellibro.com/libro-serie-desarrolladores-aplicaciones-xml-con-xml-suite/1096337/2900001128466 
         </web>
			<precio>50.96</precio>
		</libro>
		<libro isbn="ISBN9782746049581" nivel="avanzado">
			<titulo>LIBROS - XML PRACTICO. BASES ESENCIALES, CONCEPTOS Y CASOS PRACTICOS</titulo>
			<autores>
				<autor>BOULANGER, THIERRY</autor>
			</autores>
			<editorial>ENI</editorial>
			<anyo>2012</anyo>
			<web>
            http://www.casadellibro.com/libro-xml-practico-bases-esenciales-conceptos-y-casos-practicos/1261538/2900001325392
         </web>
			<precio>26.95</precio>
		</libro>
		<libro isbn="ISBN9788441525924" nivel="intermedio">
			<titulo>DESARROLLO DE APLICACIONES WEB DINAMICAS XML Y JAVA</titulo>
			<autores>
				<autor>PARSONS, DAVID</autor>
			</autores>
			<editorial>ANAYA</editorial>
			<anyo>2017</anyo>
			<web>
            http://www.casadellibro.com/libro-desarrollo-de-aplicaciones-web-dinamicas-xml-y-java-incluye-cd-programacion/1260111/2900001323752
         </web>
			<precio>52.70</precio>
		</libro>
		<libro isbn="ISBN9788441524255" nivel="avanzado">
			<titulo>SERIE DESARROLLADORES: APLICACIONES XML CON XML SUITE</titulo>
			<autores>
				<autor>PARSONS, DAVID</autor>
			</autores>
			<editorial>ANAYA</editorial>
			<anyo>2018</anyo>
			<web>
           http://www.casadellibro.com/libro-indesign-con-xml-para-disenadores-diseno-y-creatividad/1205682/2900001260950
         </web>
			<precio>25.60</precio>
		</libro>
	</libreria>
	<libreria nombre="Amazon" web="www.amazon.com">
		<libro isbn="ISBN9780231559678" nivel="avanzado">
			<titulo>XML: Visual QuickStart Guide (2nd Edition)</titulo>
			<autores>
				<autor>Kevin Howard Goldberg</autor>
			</autores>
			<editorial>PEACHPIT PRESS</editorial>
			<anyo>2015</anyo>
			<web>
           http://www.amazon.com/XML-Visual-QuickStart-Guide-2nd
         </web>
			<precio moneda="Dolar">23.09</precio>
		</libro>
		<libro isbn="ISBN9780470114872" nivel="avanzado">
			<titulo>Beginning XML, 4th Edition</titulo>
			<autores>
				<autor>David Hunter</autor>
				<autor>Jeff Rafter</autor>
				<autor>Joe Fawcett</autor>
				<autor>Eric van der Vlist</autor>
				<autor>Danny Ayers</autor>
				<autor>Jon Duckett</autor>
				<autor>Andrew Watt</autor>
				<autor>Linda McKinnon</autor>
			</autores>
			<editorial>Wiley Publishing</editorial>
			<anyo>2017</anyo>
			<web>
         http://www.amazon.com/Beginning-XML-4th-Programmer/
         </web>
			<precio moneda="Dolar">26.39</precio>
		</libro>
		<libro isbn="ISBN9780596004200" nivel="avanzado">
			<titulo>Learning XML, Second Edition</titulo>
			<autores>
				<autor>Erik Ray</autor>
			</autores>
			<editorial>O'Reilly</editorial>
			<anyo>2019</anyo>
			<web>
        http://www.amazon.com/Learning-XML-Second-Erik-Ray/
         </web>
			<precio moneda="Dolar">21.50</precio>
		</libro>
	</libreria>
</resultado>
