<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises [
	<!ELEMENT paises (pais*)>
	<!ELEMENT pais (nombre?, unionEuropea?, otan?)> 
	<!ELEMENT nombre (#PCDATA)> 
	<!ELEMENT unionEuropea EMPTY> 
	<!ELEMENT otan EMPTY> 
]>
<paises>
	<pais>
		<nombre>España</nombre>
		<unionEuropea/>
		<otan/>
	</pais>
	<pais>
		<nombre>Noruega</nombre>
	</pais>
	<pais>
		<nombre>Austria</nombre>
		<unionEuropea/>
	</pais>
</paises>

<!-- La etiqueta paises no estaba definida y nombre no es una etiqueta vacia, además de que hay algunas etiqutas que no están presentes-->