<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vuelos [
	<!ELEMENT vuelos (vuelo*)> 
	<!ELEMENT vuelo (origen, destino)+> 
	<!ELEMENT origen (#PCDATA)> 
	<!ELEMENT destino (#PCDATA)> 
]>
<vuelos>
	<vuelo>
		<origen>Valencia (VLC)</origen>
		<destino>Londres Heathrow (LHR)</destino>
	</vuelo>
	<vuelo>
		<origen>Paris Charles de Gaulle (CDG)</origen>
		<destino>Berlín Schönefeld (SFX)</destino>
	</vuelo>
</vuelos>

<!-- La etiqueta destino no esta definida, además de que tenemos presente las etiquetas origen y destino mas de una vez -->