<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marcadores [
	<!ELEMENT marcadores (marcador)*> 
	<!ELEMENT marcador (nombre, uri)> 
	<!ELEMENT nombre (#PCDATA)> 
	<!ELEMENT uri (#PCDATA)>]>
<marcadores>
	<marcador>
		<nombre>W3C</nombre>
		<uri>http://www.w3.org/</uri>
	</marcador>
	<marcador>
		<nombre>Web Hypertext Application Technology Working Group (WHATWG)</nombre>
		<uri>http://www.whatwg.org/</uri>
	</marcador>
</marcadores>

<!-- La etiqueta raiz definida en el DTD no es la etiqueta marcadores, además de que la etiqueta marcador esta más de una vez
Hay que decir qu ela etiqueta raiz es marcadores y que marcador esta más de una vez (*/+) -->