=== Chicotjr5/ASIR-CETI/ASIR/1º AÑO/Lenguaje de Marcas/UT-6/Schema/Ejercicio_5/Ejercicio5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Tabla_Periodica" type="tipotabla"/>
<xs:complexType name="tipotabla">
	<xs:sequence>
		<xs:element name="Atomo" type="tipoatomo" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

	<xs:complexType name="tipoatomo">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="Simbolo">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z][a-z]{0,2}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="numero_atomico" type="xs:int"/>
			<xs:element name="peso_atomico" type="xs:int"/>
			<xs:element name="punto_ebullicion" type="tipopunto"/>
			<xs:element name="densidad" type="tipoden"/>
		</xs:sequence>		
		<xs:attribute name="Estado">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Líquido"/>
					<xs:enumeration value="Gaseoso"/>
					<xs:enumeration value="Sólido"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="tipoden">
		<xs:simpleContent>
			<xs:extension base="xs:float">
				<xs:attribute name="unidades" type="xs:string" use="required"/>						
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="tipopunto">
		<xs:simpleContent>
			<xs:extension base="xs:float">
			<xs:attribute name="unidades" default="centigrados">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="centigrados"/>
						<xs:enumeration value="gramos"/>
					</xs:restriction>
				</xs:simpleType>					
			</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	
</xs:schema>

=== Chicotjr5/ASIR-CETI/ASIR/1º AÑO/Lenguaje de Marcas/UT-6/Schema/Ejercicio_5/Ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Archivo XML de muestra generado con XMLSpy v2022 rel. 2 (x64) (http://www.altova.com)-->
<Tabla_Periodica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio5.xsd">
	<Atomo Estado="Sólido">
		<nombre>String</nombre>
		<Simbolo>A</Simbolo>
		<numero_atomico>0</numero_atomico>
		<peso_atomico>0</peso_atomico>
		<punto_ebullicion unidades="gramos">3.141590118408203125</punto_ebullicion>
		<densidad unidades="String">3.141590118408203125</densidad>
	</Atomo>
	<Atomo Estado="Sólido">
		<nombre>String</nombre>
		<Simbolo>A</Simbolo>
		<numero_atomico>0</numero_atomico>
		<peso_atomico>0</peso_atomico>
		<punto_ebullicion unidades="centigrados">3.141590118408203125</punto_ebullicion>
		<densidad unidades="String">3.141590118408203125</densidad>
	</Atomo>
	<Atomo Estado="Sólido">
		<nombre>String</nombre>
		<Simbolo>A</Simbolo>
		<numero_atomico>0</numero_atomico>
		<peso_atomico>0</peso_atomico>
		<punto_ebullicion unidades="gramos">3.141590118408203125</punto_ebullicion>
		<densidad unidades="String">3.141590118408203125</densidad>
	</Atomo>
</Tabla_Periodica>
